[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting_dapp = "AqVFH6Vq5whfoYGWKtViGpd2oHCNCHi4nc7F8RDNFHxx"

[programs.devnet]
voting_dapp = "AqVFH6Vq5whfoYGWKtViGpd2oHCNCHi4nc7F8RDNFHxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
